<script setup lang="ts">
import { computed } from 'vue';
import {
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    Archive,
    Ban,
    BadgeCheck,
    BellRing,
    BookOpen,
    Brain,
    CalendarCheck2,
    CalendarClock,
    CalendarDays,
    CalendarPlus2,
    ChartColumn,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Circle,
    CircleCheck,
    CircleDollarSign,
    CircleX,
    ClipboardList,
    ClipboardPenLine,
    Clock3,
    ClockAlert,
    Cloud,
    Compass,
    Contact,
    Copy,
    Download,
    ExternalLink,
    Eye,
    EyeOff,
    FilePlus2,
    FileText,
    FolderArchive,
    Filter,
    Gamepad2,
    Grid3X3,
    HandCoins,
    Heart,
    HeartHandshake,
    HeartPulse,
    HelpCircle,
    ImagePlus,
    Info,
    Languages,
    Layers2,
    LayoutDashboard,
    Link,
    Link2,
    LoaderCircle,
    Lock,
    LogOut,
    Maximize,
    Mail,
    Menu,
    Mic,
    MicOff,
    MessageCircle,
    MessageCircleHeart,
    Moon,
    Minimize,
    NotebookPen,
    PanelLeftClose,
    PanelLeftOpen,
    PauseCircle,
    Palette,
    Pencil,
    PhoneOff,
    Printer,
    Plus,
    RefreshCcw,
    RefreshCw,
    Save,
    Search,
    Settings,
    Shield,
    ShieldAlert,
    ShieldCheck,
    Siren,
    Sparkles,
    Sprout,
    Sun,
    Trash2,
    TrendingUp,
    TriangleAlert,
    Trophy,
    UserCheck,
    UserPlus,
    UserRound,
    UserRoundCog,
    UserRoundPlus,
    UsersRound,
    Video,
    VideoOff,
    WalletCards,
    Wind,
    X,
} from '@lucide/vue';

interface Props {
    name: string;
    size?: number;
    strokeWidth?: number;
    ariaHidden?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
    size: 18,
    strokeWidth: 2,
    ariaHidden: true,
});

const fallbackIconName = 'Circle';

const iconMap: Record<string, object> = {
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    Archive,
    Ban,
    BadgeCheck,
    BellRing,
    BookOpen,
    Brain,
    CalendarCheck2,
    CalendarClock,
    CalendarDays,
    CalendarPlus2,
    ChartColumn,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Circle,
    CircleCheck,
    CircleDollarSign,
    CircleX,
    ClipboardList,
    ClipboardPenLine,
    Clock3,
    ClockAlert,
    Cloud,
    Compass,
    Contact,
    Copy,
    Download,
    ExternalLink,
    Eye,
    EyeOff,
    FilePlus2,
    FileText,
    FolderArchive,
    Filter,
    Gamepad2,
    Grid3X3,
    HandCoins,
    Heart,
    HeartHandshake,
    HeartPulse,
    HelpCircle,
    ImagePlus,
    Info,
    Languages,
    Layers2,
    LayoutDashboard,
    Link,
    Link2,
    LoaderCircle,
    Lock,
    LogOut,
    Maximize,
    Mail,
    Menu,
    Mic,
    MicOff,
    MessageCircle,
    MessageCircleHeart,
    Moon,
    Minimize,
    NotebookPen,
    PanelLeftClose,
    PanelLeftOpen,
    PauseCircle,
    Palette,
    Pencil,
    PhoneOff,
    Printer,
    Plus,
    RefreshCcw,
    RefreshCw,
    Save,
    Search,
    Settings,
    Shield,
    ShieldAlert,
    ShieldCheck,
    Siren,
    Sparkles,
    Sprout,
    Sun,
    Trash2,
    TrendingUp,
    TriangleAlert,
    Trophy,
    UserCheck,
    UserPlus,
    UserRound,
    UserRoundCog,
    UserRoundPlus,
    UsersRound,
    Video,
    VideoOff,
    WalletCards,
    Wind,
    X,
};

const iconComponent = computed(() => {
    return iconMap[props.name] ?? iconMap[fallbackIconName];
});
</script>

<template>
    <component
        :is="iconComponent"
        :size="size"
        :stroke-width="strokeWidth"
        :aria-hidden="ariaHidden"
    />
</template>
