<script setup>
import { computed, onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import axios from 'axios';
import AppIcon from '../components/base/AppIcon.vue';

const route = useRoute(); const mode = ref('computer'); const board = ref(Array(9).fill(null)); const current = ref('X'); const history = ref([]); const result = ref(''); const loading = ref(true); const error = ref('');
const winningLines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
const pieces = { X: [], O: [] }; const winningLine = computed(() => winningLines.find(([a,b,c]) => board.value[a] && board.value[a] === board.value[b] && board.value[a] === board.value[c]) ?? null); const over = computed(() => Boolean(winningLine.value) || board.value.every(Boolean));
const winMark = computed(() => winningLine.value ? board.value[winningLine.value[0]] : null);
const restart = () => { board.value = Array(9).fill(null); current.value = 'X'; history.value = []; result.value = ''; finished.value = false; pieces.X.length = 0; pieces.O.length = 0; };
const place = async (index, mark = current.value) => { if (over.value || board.value[index] || (mode.value === 'computer' && mark !== 'X')) return; board.value[index] = mark; board.value = [...board.value]; pieces[mark].push(index); history.value.push({ mark, index }); if (pieces[mark].length > 3) { const old = pieces[mark].shift(); board.value[old] = null; board.value = [...board.value]; } if (winMark.value || over.value) { result.value = winMark.value ?? 'draw'; finished.value = true; await finish(); return; } current.value = mark === 'X' ? 'O' : 'X'; if (mode.value === 'computer' && current.value === 'O') window.setTimeout(computerMove, 360); };
const computerMove = () => { if (over.value) return; const available = board.value.map((cell, i) => cell ? null : i).filter(i => i !== null); if (available.length) place(available[Math.floor(Math.random() * available.length)], 'O'); };
const finish = async () => { try { await axios.post('/api/gamekit/tictactoe/play/' + route.params.token + '/result', { result: result.value === 'X' ? 'win' : result.value === 'O' ? 'loss' : 'draw', moves: history.value }); } catch { /* resultado visual permanece disponível */ } };
onMounted(async () => { try { mode.value = (await axios.get('/api/gamekit/tictactoe/play/' + route.params.token)).data.session.mode ?? 'computer'; } catch { error.value = 'Esta partida não está mais disponível.'; } finally { loading.value = false; } });
</script>
<template><main class="min-h-screen bg-[#f4f6f3] px-4 py-8 sm:px-6 sm:py-12"><section class="mx-auto w-full max-w-lg"><div v-if="loading" class="rounded-3xl bg-white p-12 text-center text-sm text-[var(--spa-ink-muted)]">Carregando jogo...</div><div v-else-if="error" class="rounded-3xl bg-white p-12 text-center text-sm text-red-700">{{ error }}</div><div v-else class="space-y-5"><header class="rounded-3xl bg-white p-6 text-center shadow-sm sm:p-8"><span class="mx-auto flex size-14 items-center justify-center rounded-2xl bg-[var(--spa-accent-soft)] text-[var(--spa-accent)]"><AppIcon name="Grid3X3" class="size-7" /></span><h1 class="mt-4 text-2xl font-semibold text-[var(--spa-ink)]">Jogo da Velha Mutante</h1><p class="mt-2 text-sm leading-6 text-[var(--spa-ink-muted)]">Você pode ter até três peças. A mais antiga fica marcada e desaparece quando você coloca a quarta.</p></header><section class="rounded-3xl bg-white p-5 shadow-sm sm:p-8"><div class="mx-auto grid max-w-xs grid-cols-3 gap-3"> <button v-for="(cell,index) in board" :key="index" class="aspect-square rounded-2xl border-2 border-[var(--spa-border)] bg-[var(--spa-surface-muted)] text-4xl font-bold transition hover:border-[var(--spa-accent)] disabled:cursor-default" :class="cell === 'X' ? 'text-[var(--spa-accent)]' : 'text-slate-500'" :disabled="Boolean(cell) || over || (mode === 'computer' && current === 'O')" type="button" @click="place(index, mode === 'local' ? current : 'X')">{{ cell }}</button></div><p class="mt-5 text-center text-sm font-semibold text-[var(--spa-ink)]">{{ winMark ? `Vitória de ${winMark}!` : over ? 'Empate!' : `Vez de ${current}` }}</p><button v-if="over" class="btn-primary mx-auto mt-4" type="button" @click="restart">Jogar novamente</button></section></div></section></main></template>
