<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import axios from 'axios';
import AppIcon from '../components/base/AppIcon.vue';
import TemporaryLinkCard from '../components/gamekit/TemporaryLinkCard.vue';
import LocalizedDateInput from '../components/base/LocalizedDateInput.vue';

const router = useRouter();
const patients = ref([]), routines = ref([]), blocks = ref([]), editingBlock = ref(null), editingId = ref(null);
const publicUrl = ref(''), saving = ref(false), aiLoading = ref(false), error = ref(''), message = ref('');
const form = reactive({ name: 'Minha rotina diária', patient_id: null, reference_date: '', summary: '', theme: 'Equilíbrio entre estudo, descanso e autocuidado', age_group: 'Adolescente', block_count: 6 });
const categories = { study: { label: 'Estudo e trabalho', icon: 'BookOpen', color: 'bg-blue-50 text-blue-700 border-blue-200' }, rest: { label: 'Descanso e sono', icon: 'Moon', color: 'bg-violet-50 text-violet-700 border-violet-200' }, leisure: { label: 'Lazer', icon: 'Sparkles', color: 'bg-amber-50 text-amber-700 border-amber-200' }, self_care: { label: 'Autocuidado', icon: 'Heart', color: 'bg-rose-50 text-rose-700 border-rose-200' } };
const defaultBlock = () => ({ start_time: '08:00', duration_minutes: 60, title: '', description: '', category: 'study', icon: 'BookOpen' });
const categorySummary = computed(() => Object.entries(categories).map(([key, meta]) => ({ key, ...meta, count: blocks.value.filter(block => block.category === key).length })));
const sortedBlocks = computed(() => [...blocks.value].sort((a, b) => String(a.start_time).localeCompare(String(b.start_time))));
const blockStyle = (block) => ({ marginTop: (Math.max(0, (Number(block.start_time?.slice(0, 2) ?? 0) - 6) * 8)) + 'px' });
const load = async () => { try { const patientData = (await axios.get('/api/patients', { params: { per_page: 1000, status: 'all' } })).data; patients.value = patientData.data ?? []; routines.value = (await axios.get('/api/gamekit/routines')).data.routines ?? []; } catch { /* opcional */ } };
const addBlock = () => { blocks.value.push({ ...defaultBlock(), title: 'Nova atividade' }); editingBlock.value = blocks.value.length - 1; };
const editBlock = (index) => { editingBlock.value = index; };
const removeBlock = (index) => { if (window.confirm('Excluir este bloco da rotina?')) blocks.value.splice(index, 1); };
const closeBlock = () => { editingBlock.value = null; };
const reset = () => { editingId.value = null; form.name = 'Minha rotina diária'; form.patient_id = null; form.reference_date = ''; form.summary = ''; form.theme = 'Equilíbrio entre estudo, descanso e autocuidado'; form.age_group = 'Adolescente'; form.block_count = 6; blocks.value = []; publicUrl.value = ''; };
const generateWithAi = async () => { aiLoading.value = true; error.value = ''; message.value = ''; try { const data = (await axios.post('/api/gamekit/routines/ai-generate', { theme: form.theme, age_group: form.age_group, summary: form.summary, block_count: form.block_count })).data; blocks.value = data.blocks ?? []; if (form.name === 'Minha rotina diária') form.name = 'Rotina gerada com IA'; message.value = 'Rotina gerada com IA. Revise os blocos antes de salvar.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível gerar a rotina com IA.'; } finally { aiLoading.value = false; } };
const saveRoutine = async () => { if (!blocks.value.length) { error.value = 'Adicione pelo menos um bloco à rotina.'; return; } saving.value = true; error.value = ''; const wasEditing = editingId.value; try { const payload = { ...form, blocks: blocks.value }; const response = wasEditing ? await axios.put('/api/gamekit/routines/' + wasEditing, payload) : await axios.post('/api/gamekit/routines', payload); const saved = response.data; routines.value = wasEditing ? routines.value.map(item => item.id === saved.id ? saved : item) : [saved, ...routines.value]; editingId.value = null; message.value = wasEditing ? 'Rotina atualizada com uma nova versão.' : 'Rotina salva e vinculada ao paciente.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível salvar a rotina.'; } finally { saving.value = false; } };
const editRoutine = (routine) => { editingId.value = routine.id; Object.assign(form, { name: routine.name, patient_id: routine.patient_id, reference_date: routine.reference_date ?? '', summary: routine.current_version?.summary ?? '' }); blocks.value = (routine.current_version?.blocks ?? []).map(block => ({ start_time: String(block.start_time).slice(0, 5), duration_minutes: block.duration_minutes, title: block.title, description: block.description ?? '', category: block.category, icon: block.icon })); window.scrollTo({ top: 0, behavior: 'smooth' }); };
const deleteRoutine = async (routine) => { if (!window.confirm('Excluir esta rotina e suas versões?')) return; try { await axios.delete('/api/gamekit/routines/' + routine.id); routines.value = routines.value.filter(item => item.id !== routine.id); message.value = 'Rotina excluída.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível excluir a rotina.'; } };
const createLink = async (routine) => { try { const data = (await axios.post('/api/gamekit/routines/' + routine.id + '/link')).data; publicUrl.value = data.url; await navigator.clipboard?.writeText(data.url); message.value = 'Link temporário copiado.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível gerar o link.'; } };
onMounted(load);
</script>

<template>
    <main class="page-shell space-y-6">
        <header class="page-header"><div class="page-header__content"><button class="btn-secondary mb-4" type="button" @click="router.push('/gamekit')"><AppIcon name="ArrowLeft" class="size-4" />Voltar para o GameKit</button><p class="section-kicker">GameKit Psi · Organizador de rotina</p><h1 class="page-header__title">Um dia possível, no seu ritmo</h1><p class="page-header__description">Monte uma rotina visual junto com o paciente, equilibrando compromissos e cuidado.</p></div></header>
        <p v-if="message" class="rounded-2xl border border-[#c9d8cd] bg-[#edf4ef] px-4 py-3 text-sm text-[#365341]">{{ message }}</p><p v-if="error" class="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ error }}</p>
        <section class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><div class="space-y-5">
        <section class="surface-panel p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div><p class="section-kicker">Nova rotina</p><h2 class="text-lg font-semibold text-[var(--spa-ink)]">Configuração</h2></div><button v-if="editingId" class="btn-secondary" type="button" @click="reset">Nova rotina</button></div><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="field-label">Nome da rotina<input v-model="form.name" class="field-input mt-1" /></label><label class="field-label">Vincular ao paciente<select v-model="form.patient_id" class="field-input mt-1"><option :value="null">Não vincular agora</option><option v-for="patient in patients" :key="patient.id" :value="patient.id">{{ patient.name }}</option></select></label><label class="field-label">Data de referência (dd/mm/aaaa)<LocalizedDateInput v-model="form.reference_date" class="field-input mt-1" aria-label="Data de referência" /></label><label class="field-label">Resumo para a sessão<textarea v-model="form.summary" class="field-input mt-1 min-h-12" placeholder="Ex.: priorizar pausas e sono regular" /></label></div></section>
            <section class="surface-panel border-[var(--spa-accent)]/30 bg-[var(--spa-accent-soft)] p-5 sm:p-6"><div class="flex items-start justify-between gap-4"><div><p class="section-kicker">Assistente de rotina</p><h2 class="text-lg font-semibold text-[var(--spa-ink)]">Gerar uma sugestão com IA</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">A sugestão aparece para revisão. Você decide o que salvar.</p></div><AppIcon name="Sparkles" class="size-6 text-[var(--spa-accent)]" /></div><div class="mt-5 grid gap-4 md:grid-cols-3"><label class="field-label md:col-span-2">Tema ou objetivo<input v-model="form.theme" class="field-input mt-1" placeholder="Ex.: organizar estudos sem esquecer pausas" /></label><label class="field-label">Faixa etária<select v-model="form.age_group" class="field-input mt-1"><option>Criança</option><option>Adolescente</option><option>Adulto</option><option>Idoso</option></select></label><label class="field-label">Momentos no dia<select v-model.number="form.block_count" class="field-input mt-1"><option :value="4">4 momentos</option><option :value="6">6 momentos</option><option :value="8">8 momentos</option><option :value="10">10 momentos</option><option :value="12">12 momentos</option></select></label></div><button class="btn-primary mt-5" type="button" :disabled="aiLoading" @click="generateWithAi"><AppIcon name="Sparkles" class="size-4" />{{ aiLoading ? 'Gerando rotina...' : 'Gerar com IA' }}</button></section>
            <section class="surface-panel p-5 sm:p-6"><div class="flex items-center justify-between gap-3"><div><p class="section-kicker">Linha do tempo</p><h2 class="text-lg font-semibold text-[var(--spa-ink)]">{{ blocks.length }} blocos no dia</h2></div><button class="btn-primary" type="button" @click="addBlock"><AppIcon name="Plus" class="size-4" />Adicionar bloco</button></div><div v-if="sortedBlocks.length" class="mt-6 border-l-2 border-[var(--spa-border)] pl-5"><article v-for="block in sortedBlocks" :key="block.id ?? block.start_time + block.title" class="relative mb-4 rounded-2xl border bg-white p-4 transition hover:shadow-sm" :class="categories[block.category]?.color ?? 'border-[var(--spa-border)]'" :style="blockStyle(block)"><span class="absolute -left-[31px] top-5 flex size-4 rounded-full border-4 border-[var(--spa-surface)] bg-[var(--spa-accent)]"></span><div class="flex items-start justify-between gap-3"><div class="flex items-start gap-3"><span class="flex size-10 items-center justify-center rounded-xl bg-white"><AppIcon :name="block.icon || categories[block.category]?.icon || 'CircleCheck'" class="size-5" /></span><div><p class="text-xs font-bold uppercase tracking-wide text-[var(--spa-ink-muted)]">{{ block.start_time }} · {{ block.duration_minutes }} min</p><h3 class="mt-1 font-semibold text-[var(--spa-ink)]">{{ block.title || 'Atividade sem título' }}</h3><p class="mt-1 text-xs font-semibold text-[var(--spa-ink-muted)]">{{ categories[block.category]?.label }}</p><p v-if="block.description" class="mt-2 text-sm leading-5 text-[var(--spa-ink-muted)]">{{ block.description }}</p></div></div><div class="flex gap-1"><button class="inline-flex size-9 items-center justify-center rounded-xl text-[var(--spa-ink-muted)] hover:bg-white" type="button" aria-label="Editar bloco" @click="editBlock(blocks.indexOf(block))"><AppIcon name="Pencil" class="size-4" /></button><button class="inline-flex size-9 items-center justify-center rounded-xl text-red-600 hover:bg-white" type="button" aria-label="Excluir bloco" @click="removeBlock(blocks.indexOf(block))"><AppIcon name="Trash2" class="size-4" /></button></div></div></article></div><div v-else class="mt-6 rounded-2xl border border-dashed border-[var(--spa-border)] p-8 text-center"><AppIcon name="Clock3" class="mx-auto size-8 text-[var(--spa-ink-muted)]" /><p class="mt-3 text-sm text-[var(--spa-ink-muted)]">Adicione o primeiro bloco ou gere uma sugestão com IA.</p></div><div class="mt-6 flex justify-end border-t border-[var(--spa-border)] pt-5"><button class="btn-primary" type="button" :disabled="saving" @click="saveRoutine"><AppIcon name="Save" class="size-4" />{{ saving ? 'Salvando...' : (editingId ? 'Salvar nova versão' : 'Salvar rotina') }}</button></div></section>
        </div><aside class="space-y-5"><section class="surface-panel p-5"><p class="section-kicker">Equilíbrio do dia</p><h2 class="mt-1 text-lg font-semibold text-[var(--spa-ink)]">Categorias</h2><div class="mt-4 space-y-3"><div v-for="item in categorySummary" :key="item.key" class="flex items-center justify-between rounded-2xl border border-[var(--spa-border)] bg-white p-3"><span class="flex items-center gap-2 text-sm font-semibold text-[var(--spa-ink)]"><AppIcon :name="item.icon" class="size-4" />{{ item.label }}</span><span class="rounded-full bg-[var(--spa-surface-muted)] px-2 py-1 text-xs font-bold text-[var(--spa-ink-muted)]">{{ item.count }}</span></div></div></section><TemporaryLinkCard v-if="publicUrl" :url="publicUrl" label="Link da rotina" /></aside></section>
        <section v-if="routines.length" class="surface-panel p-5 sm:p-6"><div><p class="section-kicker">Rotinas salvas</p><h2 class="text-lg font-semibold text-[var(--spa-ink)]">Histórico de rotinas</h2></div><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><article v-for="routine in routines" :key="routine.id" class="rounded-2xl border border-[var(--spa-border)] bg-white p-4"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold text-[var(--spa-ink)]">{{ routine.name }}</h3><p class="mt-1 text-xs text-[var(--spa-ink-muted)]">{{ routine.patient?.name ?? 'Sem paciente vinculado' }} · versão {{ routine.current_version?.version ?? routine.current_version ?? '—' }}</p></div><button class="text-xs font-semibold text-red-700" type="button" @click="deleteRoutine(routine)">Excluir</button></div><div class="mt-4 flex flex-wrap gap-2"><button class="btn-secondary" type="button" @click="editRoutine(routine)">Editar</button><button class="btn-secondary" type="button" @click="createLink(routine)"><AppIcon name="Link" class="size-4" />Link</button></div></article></div></section>
        <section v-if="editingBlock !== null" class="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/40 p-4" role="dialog" aria-modal="true" aria-label="Editar bloco"><div class="w-full max-w-xl rounded-3xl bg-[var(--spa-surface)] p-5 shadow-2xl sm:p-6"><div class="flex items-start justify-between border-b border-[var(--spa-border)] pb-4"><div><p class="section-kicker">Editar bloco</p><h2 class="mt-1 text-lg font-semibold text-[var(--spa-ink)]">Uma atividade de cada vez</h2></div><button class="inline-flex size-10 items-center justify-center rounded-xl border border-[var(--spa-border)] text-[var(--spa-ink-muted)]" type="button" aria-label="Fechar" @click="closeBlock"><AppIcon name="X" class="size-5" /></button></div><div v-if="blocks[editingBlock]" class="mt-5 grid gap-4 sm:grid-cols-2"><label class="field-label">Horário<input v-model="blocks[editingBlock].start_time" class="field-input mt-1" type="time" /></label><label class="field-label">Duração<select v-model.number="blocks[editingBlock].duration_minutes" class="field-input mt-1"><option :value="15">15 min</option><option :value="30">30 min</option><option :value="45">45 min</option><option :value="60">60 min</option><option :value="90">90 min</option><option :value="120">120 min</option></select></label><label class="field-label sm:col-span-2">Atividade<input v-model="blocks[editingBlock].title" class="field-input mt-1" placeholder="Ex.: Caminhada" /></label><label class="field-label sm:col-span-2">Categoria<select v-model="blocks[editingBlock].category" class="field-input mt-1"><option value="study">Estudo e trabalho</option><option value="rest">Descanso e sono</option><option value="leisure">Lazer</option><option value="self_care">Autocuidado</option></select></label><label class="field-label sm:col-span-2">Observação opcional<textarea v-model="blocks[editingBlock].description" class="field-input mt-1 min-h-20" placeholder="Como tornar esse momento possível?" /></label></div><div class="mt-5 flex justify-end"><button class="btn-primary" type="button" @click="closeBlock">Concluir edição</button></div></div></section>
    </main>
</template>
