<script setup>
import { reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import axios from 'axios';
import AppIcon from '../components/base/AppIcon.vue';

const loading = ref(false), saving = ref(false), aiLoading = ref(false), message = ref(''), error = ref('');
const router = useRouter();
const session = ref(null), selectedGame = ref(null), publicUrl = ref(''), aiCards = ref([]), templates = ref([]), editingTemplateId = ref(null), historySessions = ref([]), historyResponses = ref([]), selectedHistorySession = ref(null), selectedHistoryPatientId = ref(null), patients = ref([]), historySaving = ref(false);
const gameCatalog = [{ id: 'association_memory', name: 'Associação e memória', description: 'Explore situações, pensamentos e possibilidades de resposta em cartas guiadas.', audience: 'Crianças, adolescentes e adultos', icon: 'Brain' }, { id: 'memory', name: 'Jogo da memória', description: 'Encontre pares de emoções e conceitos e converse sobre as associações que surgirem.', audience: 'Adolescentes e adultos', icon: 'Layers2' }];
const aiForm = reactive({ age_group: 'Adolescente', theme: 'Habilidades sociais', difficulty: 'Média', activity_type: 'Associação e memória', card_count: 6, language: 'pt-BR' });
const templateName = ref('');
const sessionStatusLabel = (status) => ({ draft: 'Rascunho', active: 'Em andamento', finished: 'Finalizado' }[status] ?? status);
const closeTemplateEditor = () => { editingTemplateId.value = null; templateName.value = ''; aiCards.value = []; };
const chooseGame = (game) => { if (game.id === 'memory') { router.push('/gamekit/memory'); return; } selectedGame.value = game; aiForm.activity_type = game.name; loadTemplates(); loadHistory(); };
const backToGameCatalog = () => { selectedGame.value = null; closeTemplateEditor(); closeHistory(); templates.value = []; historySessions.value = []; patients.value = []; };
const closeHistory = () => { selectedHistorySession.value = null; historyResponses.value = []; selectedHistoryPatientId.value = null; };
const fail = (e, fallback) => { error.value = e?.response?.data?.message ?? fallback; };
const loadTemplates = async () => { if (!selectedGame.value) return; try { templates.value = (await axios.get('/api/gamekit/templates')).data.templates ?? []; } catch { /* opcional */ } };
const loadHistory = async () => { if (!selectedGame.value) return; try { const { data } = await axios.get('/api/gamekit/sessions', { params: { with_responses: 1 } }); historySessions.value = Array.isArray(data) ? data : []; const patientsData = (await axios.get('/api/patients', { params: { per_page: 1000, status: 'all' } })).data; patients.value = patientsData.data ?? []; } catch { /* histórico opcional */ } };
const openHistory = async (item) => { try { const { data } = await axios.get('/api/gamekit/sessions/' + item.id); selectedHistorySession.value = data; selectedHistoryPatientId.value = data.patient_id ?? null; historyResponses.value = data.responses ?? []; } catch (e) { fail(e, 'Não foi possível carregar as respostas.'); } };
const saveHistory = async () => { if (!selectedHistorySession.value) return; historySaving.value = true; try { await axios.post('/api/gamekit/sessions/' + selectedHistorySession.value.id + '/review', { patient_id: selectedHistoryPatientId.value || null, responses: historyResponses.value.map(response => ({ id: response.id, include_in_record: response.include_in_record ?? false, note: response.note || null })) }); message.value = 'Vínculo da sessão atualizado.'; selectedHistorySession.value.patient_id = selectedHistoryPatientId.value || null; } catch (e) { fail(e, 'Não foi possível salvar o vínculo.'); } finally { historySaving.value = false; } };
const generateWithAi = async () => { aiLoading.value = true; error.value = ''; try { aiCards.value = (await axios.post('/api/gamekit/ai/generate', aiForm)).data.cards ?? []; message.value = 'Cartas geradas. Revise o conteúdo antes de salvar.'; } catch (e) { fail(e, 'Não foi possível gerar as cartas por IA.'); } finally { aiLoading.value = false; } };
const saveTemplate = async () => { if (!templateName.value.trim() || (!aiCards.value.length && !editingTemplateId.value)) return; saving.value = true; const wasEditing = editingTemplateId.value; const endpoint = wasEditing ? '/api/gamekit/templates/' + wasEditing : '/api/gamekit/templates'; try { let response; if (wasEditing && !aiCards.value.length) response = await axios.put(endpoint, { name: templateName.value }); else { const payload = { ...aiForm, name: templateName.value, cards: aiCards.value }; response = wasEditing ? await axios.put(endpoint, payload) : await axios.post(endpoint, payload); } const saved = response.data; if (wasEditing) { const index = templates.value.findIndex(template => String(template.id) === String(wasEditing)); if (index !== -1) templates.value[index] = { ...templates.value[index], ...saved, name: saved.name ?? templateName.value }; } else if (saved?.id) { templates.value.unshift(saved); } message.value = wasEditing ? 'Modelo atualizado.' : 'Modelo salvo para reutilização.'; templateName.value = ''; editingTemplateId.value = null; aiCards.value = []; } catch (e) { fail(e, 'Não foi possível salvar o modelo.'); } finally { saving.value = false; } };
const useTemplate = (template) => { editingTemplateId.value = template.id; Object.assign(aiForm, { age_group: template.age_group, theme: template.theme, activity_type: template.activity_type, difficulty: template.difficulty, duration_minutes: template.duration_minutes }); aiCards.value = (template.cards ?? template.current_cards ?? template.currentCards ?? []).map(c => ({ context: c.context, question: c.question, options: [...c.options] })); templateName.value = template.name; message.value = 'Modelo carregado para edição.'; };
const deleteTemplate = async (template) => { if (!window.confirm(`Excluir o modelo “${template.name}”?`)) return; saving.value = true; try { await axios.delete('/api/gamekit/templates/' + template.id); if (editingTemplateId.value === template.id) { editingTemplateId.value = null; templateName.value = ''; aiCards.value = []; } templates.value = templates.value.filter(item => item.id !== template.id); message.value = 'Modelo excluído.'; } catch (e) { fail(e, 'Não foi possível excluir o modelo.'); } finally { saving.value = false; } };
const startTemplate = async (template) => { saving.value = true; try { session.value = (await axios.post('/api/gamekit/templates/' + template.id + '/session')).data; message.value = 'Sessão criada a partir do modelo. Gere o link quando estiver pronto.'; } catch (e) { fail(e, 'Não foi possível iniciar a sessão.'); } finally { saving.value = false; } };
const createGame = async () => { loading.value = true; error.value = ''; try { const { data } = await axios.post('/api/gamekit/default-model', { theme: aiForm.theme }); aiCards.value = data.cards ?? []; editingTemplateId.value = null; templateName.value = `${aiForm.theme} — modelo padrão`; message.value = 'Modelo padrão gerado. Revise as cartas e salve para reutilizar.'; } catch (e) { fail(e, 'Não foi possível gerar o modelo padrão.'); } finally { loading.value = false; } };
const issueLink = async () => { if (!session.value?.id) return; saving.value = true; try { let cards = Array.isArray(session.value.cards) ? session.value.cards : []; if (!cards.length) cards = (await axios.get('/api/gamekit/sessions/' + session.value.id)).data.cards ?? []; if (!cards.length) throw new Error('Nenhuma carta disponível para salvar.'); const payload = cards.map(card => ({ prompt_a: card.prompt_a ?? card.context ?? '', prompt_b: card.prompt_b ?? card.question ?? '', options: Array.isArray(card.options) ? card.options : [] })); const { data: saved } = await axios.put('/api/gamekit/sessions/' + session.value.id, { cards: payload }); session.value = saved; const { data } = await axios.post('/api/gamekit/sessions/' + session.value.id + '/link'); publicUrl.value = data.url; await navigator.clipboard?.writeText(data.url); message.value = 'Link temporário copiado.'; } catch (e) { fail(e, e?.message === 'Nenhuma carta disponível para salvar.' ? e.message : 'Não foi possível gerar o link.'); } finally { saving.value = false; } };
const removeCard = (index) => { if (session.value?.cards?.length > 1) session.value.cards.splice(index, 1); };
const finishSession = async () => { if (!session.value?.id) return; await axios.post('/api/gamekit/sessions/' + session.value.id + '/finish'); message.value = 'Sessão finalizada.'; };
const backToBuilder = () => { session.value = null; publicUrl.value = ''; message.value = ''; error.value = ''; loadHistory(); };
</script>

<template>
<main class="page-shell space-y-6"><header class="page-header"><div class="page-header__content"><p class="section-kicker">Ferramentas de sessão</p><h1 class="page-header__title">GameKit Psi</h1><p class="page-header__description">Crie atividades terapêuticas acolhedoras, revise o conteúdo e reutilize seus modelos.</p></div></header>
<p v-if="message" class="rounded-2xl border border-[#c9d8cd] bg-[#edf4ef] px-4 py-3 text-sm text-[#365341]">{{ message }}</p><p v-if="error" class="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ error }}</p>
<section v-if="!selectedGame && !session" class="surface-panel p-5 sm:p-6"><div class="flex items-start gap-3"><div class="flex size-11 items-center justify-center rounded-2xl bg-[var(--spa-accent-soft)] text-[var(--spa-accent)]"><AppIcon name="Gamepad2" class="size-5" /></div><div><h2 class="text-lg font-semibold text-[var(--spa-ink)]">Escolha um jogo</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">O GameKit Psi reúne jogos terapêuticos para diferentes objetivos clínicos.</p></div></div><div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><button v-for="game in gameCatalog" :key="game.id" class="group rounded-2xl border border-[var(--spa-border)] bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-[var(--spa-accent)] hover:shadow-md" @click="chooseGame(game)"><span class="flex size-11 items-center justify-center rounded-2xl bg-[var(--spa-accent-soft)] text-[var(--spa-accent)]"><AppIcon :name="game.icon" class="size-5" /></span><span class="mt-4 block text-base font-semibold capitalize text-[var(--spa-ink)]">{{ game.name }}</span><span class="mt-2 block text-sm leading-5 text-[var(--spa-ink-muted)]">{{ game.description }}</span><span class="mt-4 block text-xs font-semibold text-[var(--spa-accent)]">{{ game.audience }}</span></button></div></section>
<section v-if="selectedGame && !session" class="surface-panel p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div class="flex items-start gap-3"><div class="flex size-11 items-center justify-center rounded-2xl bg-[var(--spa-accent-soft)] text-[var(--spa-accent)]"><AppIcon :name="selectedGame.icon" class="size-5" /></div><div><p class="section-kicker">Jogo selecionado</p><h2 class="text-lg font-semibold capitalize text-[var(--spa-ink)]">{{ selectedGame.name }}</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">Escolha como deseja começar. O modelo padrão é imediato; o modo IA cria cartas editáveis.</p></div></div><button class="btn-secondary shrink-0" type="button" @click="backToGameCatalog">Trocar jogo</button></div><div class="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label class="field-label">Faixa etária<select v-model="aiForm.age_group" class="field-input mt-1"><option>Criança</option><option>Adolescente</option><option>Adulto</option></select></label><label class="field-label">Tema<input v-model="aiForm.theme" class="field-input mt-1" /></label><label class="field-label">Tipo de atividade<input v-model="aiForm.activity_type" class="field-input mt-1" readonly /></label><label class="field-label">Dificuldade<select v-model="aiForm.difficulty" class="field-input mt-1"><option>Fácil</option><option>Média</option><option>Difícil</option></select></label><label class="field-label">Quantidade de cartas<select v-model.number="aiForm.card_count" class="field-input mt-1"><option :value="6">6</option><option :value="8">8</option><option :value="10">10</option><option :value="12">12</option></select></label></div><div class="mt-6 flex flex-col gap-3 border-t border-[var(--spa-border)] pt-5 sm:flex-row"><button class="btn-secondary justify-center" :disabled="loading" @click="createGame"><AppIcon name="FilePlus2" class="size-4" />{{ loading ? 'Gerando...' : 'Gerar modelo padrão' }}</button><button class="btn-primary justify-center" :disabled="aiLoading" @click="generateWithAi"><AppIcon name="Sparkles" class="size-4" />{{ aiLoading ? 'Gerando cartas...' : 'Gerar com IA' }}</button></div></section>
<section v-if="!session && (aiCards.length || editingTemplateId)" :class="editingTemplateId ? 'fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[calc(100%-2rem)] max-w-6xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-3xl bg-[var(--spa-surface)] p-5 shadow-2xl sm:p-6' : 'surface-panel p-5 sm:p-6'" :style="editingTemplateId ? { boxShadow: '0 0 0 100vmax rgba(15, 23, 42, .42)' } : undefined"><div class="flex items-start justify-between gap-4 border-b border-[var(--spa-border)] pb-4"><div class="min-w-0 flex-1"><p v-if="editingTemplateId" class="mb-2 text-lg font-semibold text-[var(--spa-ink)]">Editar modelo</p><div class="flex items-end gap-3"><label class="field-label min-w-0 flex-1">Nome do modelo<input v-model="templateName" class="field-input mt-1" placeholder="Ex.: Habilidades sociais — adolescentes" /></label><button class="btn-primary inline-flex h-10 shrink-0 items-center justify-center px-4" :disabled="saving || !templateName.trim()" @click="saveTemplate">{{ saving ? 'Salvando...' : (editingTemplateId ? 'Atualizar modelo' : 'Salvar modelo') }}</button></div></div><button v-if="editingTemplateId" class="inline-flex size-10 shrink-0 items-center justify-center rounded-xl border border-[var(--spa-border)] text-xl leading-none text-[var(--spa-ink-muted)] transition hover:bg-[var(--spa-surface-muted)] hover:text-[var(--spa-ink)]" type="button" aria-label="Fechar editor" title="Fechar" @click="closeTemplateEditor"><AppIcon name="X" class="size-5" /></button></div><p v-if="editingTemplateId && !aiCards.length" class="mt-4 text-sm text-[var(--spa-ink-muted)]">Este modelo ainda não possui cartas. Você pode renomeá-lo agora.</p><div v-if="aiCards.length" class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="(card, index) in aiCards" :key="index" class="rounded-2xl border border-[var(--spa-border)] bg-white p-4"><div class="flex items-center justify-between"><p class="text-xs font-semibold text-[var(--spa-ink-muted)]">Carta {{ index + 1 }}</p><button class="text-xs font-semibold text-red-700" type="button" @click="aiCards.splice(index, 1)">Excluir carta</button></div><label class="field-label mt-3 block">Contexto<textarea v-model="card.context" class="field-input mt-1 min-h-20 text-sm" placeholder="Contexto" /></label><label class="field-label mt-2 block">Pergunta<textarea v-model="card.question" class="field-input mt-1 min-h-16 text-sm" placeholder="Pergunta" /></label><label v-for="(_, optionIndex) in card.options" :key="optionIndex" class="field-label mt-2 block">Opção {{ optionIndex + 1 }}<input v-model="card.options[optionIndex]" class="field-input mt-1 text-sm" :placeholder="`Opção ${optionIndex + 1}`" /></label></article></div></section>
<section v-if="!session && templates.length" class="surface-panel p-5"><h2 class="text-lg font-semibold text-[var(--spa-ink)]">Modelos salvos</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">Edite o conteúdo ou exclua modelos que não serão mais usados.</p><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><div v-for="template in templates" :key="template.id" class="rounded-2xl border border-[var(--spa-border)] p-4"><div class="flex items-start justify-between gap-3"><button class="text-left" @click="useTemplate(template)"><span class="font-semibold text-[var(--spa-ink)]">{{ template.name }}</span><span class="mt-1 block text-sm text-[var(--spa-ink-muted)]">{{ template.age_group }} · {{ template.cards?.length ?? template.current_cards?.length ?? template.currentCards?.length ?? 0 }} cartas</span></button><button class="text-xs font-semibold text-red-700" :disabled="saving" @click="deleteTemplate(template)">Excluir</button></div><button class="btn-secondary mt-3 w-full" :disabled="saving" @click="startTemplate(template)">Usar em uma sessão</button></div></div></section>
<section v-if="!session && historySessions.length" class="surface-panel p-5"><div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-[var(--spa-ink)]">Histórico de respostas</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">Consulte respostas das sessões e, se desejar, vincule-as a um paciente.</p></div></div><div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6"><button v-for="item in historySessions" :key="item.id" class="min-h-24 rounded-2xl border border-[var(--spa-border)] bg-white p-3 text-left transition hover:-translate-y-0.5 hover:border-[var(--spa-accent)] hover:shadow-sm" @click="openHistory(item)"><span class="block truncate text-sm font-semibold text-[var(--spa-ink)]">{{ item.theme }}</span><span class="mt-2 block text-xs text-[var(--spa-ink-muted)]">{{ sessionStatusLabel(item.status) }}</span><span class="mt-1 block text-xs text-[var(--spa-ink-muted)]">{{ item.responses_count ?? item.responses?.length ?? 0 }} respostas</span></button></div></section>
<section v-if="!session && selectedHistorySession" class="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[calc(100%-2rem)] max-w-3xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-3xl bg-[var(--spa-surface)] p-5 shadow-2xl sm:p-6" :style="{ boxShadow: '0 0 0 100vmax rgba(15, 23, 42, .42)' }"><div class="flex items-start justify-between gap-4 border-b border-[var(--spa-border)] pb-4"><div><p class="text-xs font-semibold uppercase tracking-wide text-[var(--spa-ink-muted)]">Histórico da sessão</p><h2 class="mt-1 text-lg font-semibold text-[var(--spa-ink)]">{{ selectedHistorySession.theme }}</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">O vínculo é feito uma vez para toda a sessão.</p></div><button class="inline-flex size-10 shrink-0 items-center justify-center rounded-xl border border-[var(--spa-border)] text-xl leading-none text-[var(--spa-ink-muted)] hover:bg-[var(--spa-surface-muted)]" type="button" aria-label="Fechar histórico" @click="closeHistory"><AppIcon name="X" class="size-5" /></button></div><div class="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end"><label class="field-label flex-1">Vincular sessão ao paciente<select v-model="selectedHistoryPatientId" class="field-input mt-1"><option :value="null">Não vincular</option><option v-for="patient in patients" :key="patient.id" :value="patient.id">{{ patient.name }}</option></select></label><button class="btn-primary shrink-0" :disabled="historySaving" @click="saveHistory">{{ historySaving ? 'Salvando...' : 'Salvar vínculo' }}</button></div><div v-if="historyResponses.length" class="mt-5 grid gap-3 sm:grid-cols-2"><article v-for="response in historyResponses" :key="response.id" class="rounded-2xl border border-[var(--spa-border)] bg-white p-4"><p class="text-xs font-semibold uppercase tracking-wide text-[var(--spa-ink-muted)]">Resposta</p><p class="mt-2 text-sm font-semibold text-[var(--spa-ink)]">{{ response.card?.prompt_b ?? response.card?.prompt_a }}</p><p class="mt-2 rounded-xl bg-[var(--spa-surface-muted)] p-3 text-sm text-[var(--spa-ink-soft)]">{{ response.answer }}</p></article></div><p v-else class="mt-5 text-sm text-[var(--spa-ink-muted)]">Ainda não há respostas nesta sessão.</p></section>
<section v-if="session" class="space-y-5"><div class="surface-panel flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="section-kicker">Associação e Memória</p><h2 class="mt-1 text-xl font-semibold text-[var(--spa-ink)]">{{ session.theme }}</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">{{ session.cards?.length ?? 0 }} cartas · {{ sessionStatusLabel(session.status) }}</p></div><div class="flex flex-wrap gap-2"><button class="btn-secondary" type="button" @click="backToBuilder"><AppIcon name="ArrowLeft" class="size-4" />Voltar</button><button class="btn-primary" :disabled="saving" @click="issueLink"><AppIcon name="Link" class="size-4" />Gerar link do paciente</button></div></div><div v-if="publicUrl" class="surface-panel p-4"><p class="text-xs font-semibold uppercase tracking-wide text-[var(--spa-ink-muted)]">Link temporário</p><p class="mt-2 break-all text-sm text-[var(--spa-ink)]">{{ publicUrl }}</p></div><div v-if="session.cards?.length" class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="(card, index) in session.cards" :key="card.id ?? index" class="surface-panel p-4"><div class="flex items-center justify-between"><span class="text-xs font-semibold text-[var(--spa-ink-muted)]">Carta {{ index + 1 }}</span><button class="text-xs font-semibold text-red-700" :disabled="session.cards.length <= 1" @click="removeCard(index)">Excluir carta</button></div><label class="field-label mt-4 block">Contexto<textarea v-model="card.prompt_a" class="field-input mt-1 min-h-20 text-sm" /></label><label class="field-label mt-2 block">Pergunta<textarea v-model="card.prompt_b" class="field-input mt-1 min-h-16 text-sm" /></label><label v-for="(_, optionIndex) in card.options" :key="optionIndex" class="field-label mt-2 block">Opção {{ optionIndex + 1 }}<input v-model="card.options[optionIndex]" class="field-input mt-1 text-sm" /></label></article></div><p v-else class="surface-panel p-5 text-sm text-[var(--spa-ink-muted)]">Nenhuma carta disponível para esta sessão.</p></section>
</main>
</template>
