<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import axios from 'axios';
import AppIcon from '../components/base/AppIcon.vue';
import TemporaryLinkCard from '../components/gamekit/TemporaryLinkCard.vue';

const router = useRouter();
const saving = ref(false), aiLoading = ref(false), error = ref(''), message = ref('');
const games = ref([]), editingId = ref(null), activePairIndex = ref(null), hasDraft = ref(false);
const session = ref(null), publicUrl = ref('');
const form = reactive({ name: 'Jogo da memória — emoções', age_group: 'Adolescente', theme: 'Reconhecimento emocional', difficulty: 'Média', pair_count: 6 });
const pairBank = [['Ansiedade', 'Respirar devagar', 'Perceber sinais do corpo e criar espaço para escolher como agir.', 'sky'], ['Tristeza', 'Pedir acolhimento', 'Reconhecer a emoção e buscar uma presença segura quando necessário.', 'lavender'], ['Raiva', 'Fazer uma pausa', 'Nomear a emoção antes de responder ajuda a proteger a relação.', 'clay'], ['Alegria', 'Compartilhar', 'Perceber o que faz bem também ajuda a fortalecer vínculos.', 'sun'], ['Vergonha', 'Falar com alguém', 'A vergonha diminui quando encontra escuta sem julgamento.', 'rose'], ['Medo', 'Buscar segurança', 'Identificar apoio e próximos passos torna o desconhecido mais possível.', 'sage'], ['Frustração', 'Tentar outra vez', 'Uma pausa permite aprender com o que não saiu como esperado.', 'amber'], ['Solidão', 'Aproximar-se', 'Pequenos convites podem abrir espaço para uma conexão significativa.', 'blue'], ['Culpa', 'Reparar', 'Assumir responsabilidade e pensar em reparação é diferente de se punir.', 'moss'], ['Confusão', 'Fazer perguntas', 'Perguntar ajuda a organizar pensamentos e diminuir interpretações precipitadas.', 'violet'], ['Cansaço', 'Respeitar limites', 'Observar os próprios limites é uma forma de cuidado.', 'teal'], ['Esperança', 'Dar um próximo passo', 'A esperança pode ser transformada em uma ação pequena e possível.', 'gold']];
const iconBank = ['Wind', 'HeartHandshake', 'PauseCircle', 'Sun', 'MessageCircleHeart', 'Shield', 'CircleCheck', 'Compass', 'Sprout', 'HelpCircle', 'Cloud', 'Sparkles'];
const newPair = (index) => { const item = pairBank[index % pairBank.length]; return { label_a: item[0], label_b: item[1], concept: item[2], feedback: 'Este par conecta ' + item[0] + ' e ' + item[1] + '. O que essa relação lembra você?', icon: iconBank[index % iconBank.length], accent: item[3] }; };
const pairs = ref([]);
const activePair = computed(() => activePairIndex.value === null ? null : pairs.value[activePairIndex.value]);
const defaultPairs = () => Array.from({ length: Number(form.pair_count) }, (_, index) => newPair(index));
const generateDefaultModel = () => { editingId.value = null; pairs.value = defaultPairs(); form.name = form.theme + ' — modelo padrão'; hasDraft.value = true; message.value = 'Modelo padrão gerado. Revise os pares e salve para reutilizar.'; error.value = ''; };
const generateWithAi = async () => { aiLoading.value = true; error.value = ''; try { const { data } = await axios.post('/api/gamekit/memory/ai-generate', { age_group: form.age_group, theme: form.theme, difficulty: form.difficulty, pair_count: form.pair_count }); pairs.value = data.pairs ?? []; editingId.value = null; form.name = form.theme + ' — gerado com IA'; hasDraft.value = true; message.value = 'Pares gerados com IA. Revise cada par antes de salvar.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível gerar os pares com IA.'; } finally { aiLoading.value = false; } };
const adjustPairCount = () => { if (hasDraft.value) pairs.value = Array.from({ length: Number(form.pair_count) }, (_, index) => pairs.value[index] ?? newPair(index)); };
const openEditor = (index) => { activePairIndex.value = index; };
const closeEditor = () => { activePairIndex.value = null; };
const resetBuilder = () => { editingId.value = null; hasDraft.value = false; pairs.value = []; form.name = 'Jogo da memória — emoções'; form.age_group = 'Adolescente'; form.theme = 'Reconhecimento emocional'; form.difficulty = 'Média'; form.pair_count = 6; publicUrl.value = ''; };
const loadGames = async () => { try { games.value = (await axios.get('/api/gamekit/memory/games')).data.games ?? []; } catch { /* opcional */ } };
const saveGame = async () => { if (!pairs.value.length) return; saving.value = true; error.value = ''; const wasEditing = editingId.value; try { const payload = { ...form, pairs: pairs.value }; const response = wasEditing ? await axios.put('/api/gamekit/memory/games/' + wasEditing, payload) : await axios.post('/api/gamekit/memory/games', payload); const saved = response.data; if (wasEditing) games.value = games.value.map(item => item.id === saved.id ? saved : item); else games.value.unshift(saved); editingId.value = null; hasDraft.value = false; pairs.value = []; message.value = wasEditing ? 'Modelo atualizado.' : 'Modelo salvo para reutilização.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível salvar o modelo.'; } finally { saving.value = false; } };
const editGame = (game) => { editingId.value = game.id; hasDraft.value = false; Object.assign(form, { name: game.name, age_group: game.age_group, theme: game.theme, difficulty: game.difficulty, pair_count: game.pairs?.length ?? game.pair_count }); pairs.value = (game.pairs ?? []).map((pair, index) => ({ label_a: pair.label_a, label_b: pair.label_b, concept: pair.concept, feedback: pair.feedback, icon: pair.icon ?? iconBank[index % iconBank.length], accent: pair.accent })); };
const closeModelEditor = () => { editingId.value = null; pairs.value = []; activePairIndex.value = null; };
const deleteGame = async (game) => { if (!window.confirm('Excluir “' + game.name + '”?')) return; try { await axios.delete('/api/gamekit/memory/games/' + game.id); games.value = games.value.filter(item => item.id !== game.id); if (editingId.value === game.id) closeModelEditor(); message.value = 'Modelo excluído.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível excluir o modelo.'; } };
const duplicateGame = async (game) => { try { const saved = (await axios.post('/api/gamekit/memory/games/' + game.id + '/duplicate')).data; games.value.unshift(saved); message.value = 'Cópia criada.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível duplicar o modelo.'; } };
const startSession = async (game) => { try { session.value = (await axios.post('/api/gamekit/memory/games/' + game.id + '/sessions')).data; publicUrl.value = ''; message.value = 'Sessão criada. Gere o link quando estiver pronto.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível iniciar a sessão.'; } };
const issueLink = async () => { if (!session.value?.id) return; try { const data = (await axios.post('/api/gamekit/memory/sessions/' + session.value.id + '/link')).data; publicUrl.value = data.url; await navigator.clipboard?.writeText(data.url); message.value = 'Link temporário copiado.'; } catch (e) { error.value = e?.response?.data?.message ?? 'Não foi possível gerar o link.'; } };
onMounted(loadGames);
</script>

<template>
    <main class="page-shell space-y-6">
        <header class="page-header"><div class="page-header__content"><button class="btn-secondary mb-4" type="button" @click="router.push('/gamekit')"><AppIcon name="ArrowLeft" class="size-4" />Voltar para o GameKit</button><p class="section-kicker">GameKit Psi · Jogo da memória</p><h1 class="page-header__title">Jogo da memória</h1><p class="page-header__description">Crie um modelo terapêutico, revise os pares e reutilize a atividade em novas sessões.</p></div></header>
        <p v-if="message" class="rounded-2xl border border-[#c9d8cd] bg-[#edf4ef] px-4 py-3 text-sm text-[#365341]">{{ message }}</p><p v-if="error" class="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ error }}</p>
        <section v-if="session" class="surface-panel p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="section-kicker">Sessão pronta</p><h2 class="mt-1 text-xl font-semibold text-[var(--spa-ink)]">{{ session.game?.name }}</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">{{ session.game?.pairs?.length ?? 0 }} pares · Link válido por 8 horas</p></div><div class="flex flex-wrap gap-2"><button class="btn-secondary" type="button" @click="session = null"><AppIcon name="ArrowLeft" class="size-4" />Voltar</button><button class="btn-primary" type="button" @click="issueLink"><AppIcon name="Link" class="size-4" />Gerar link</button></div></div><TemporaryLinkCard v-if="publicUrl" class="mt-5" :url="publicUrl" label="Link do jogo da memória" /></section>
        <template v-else>
            <section class="surface-panel p-5 sm:p-6"><div class="flex items-start gap-3"><div class="flex size-11 items-center justify-center rounded-2xl bg-[var(--spa-accent-soft)] text-[var(--spa-accent)]"><AppIcon name="Brain" class="size-5" /></div><div><p class="section-kicker">Configuração da atividade</p><h2 class="text-lg font-semibold text-[var(--spa-ink)]">Escolha os parâmetros do jogo</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">Use o modelo padrão ou peça para a IA criar os pares com base no tema e na faixa etária.</p></div></div><div class="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label class="field-label">Faixa etária<select v-model="form.age_group" class="field-input mt-1"><option>Criança</option><option>Adolescente</option><option>Adulto</option></select></label><label class="field-label">Tema<input v-model="form.theme" class="field-input mt-1" /></label><label class="field-label">Dificuldade<select v-model="form.difficulty" class="field-input mt-1"><option>Fácil</option><option>Média</option><option>Difícil</option></select></label><label class="field-label">Quantidade de pares<select v-model.number="form.pair_count" class="field-input mt-1" @change="adjustPairCount"><option :value="6">6</option><option :value="8">8</option><option :value="12">12</option></select></label></div><div class="mt-6 flex flex-col gap-3 border-t border-[var(--spa-border)] pt-5 sm:flex-row"><button class="btn-secondary justify-center" type="button" @click="generateDefaultModel"><AppIcon name="FilePlus2" class="size-4" />Gerar modelo padrão</button><button class="btn-primary justify-center" type="button" :disabled="aiLoading" @click="generateWithAi"><AppIcon name="Sparkles" class="size-4" />{{ aiLoading ? 'Gerando pares...' : 'Gerar com IA' }}</button></div></section>
            <section v-if="hasDraft" class="surface-panel p-5 sm:p-6"><div class="flex items-end justify-between gap-4 border-b border-[var(--spa-border)] pb-4"><div class="min-w-0 flex-1"><p class="section-kicker">Revisão do modelo</p><label class="field-label mt-2 block">Nome do modelo<input v-model="form.name" class="field-input mt-1" /></label></div><button class="btn-primary shrink-0" type="button" :disabled="saving || !form.name.trim()" @click="saveGame"><AppIcon name="Save" class="size-4" />{{ saving ? 'Salvando...' : 'Salvar modelo' }}</button></div><div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><button v-for="(pair, index) in pairs" :key="index" class="group rounded-2xl border border-[var(--spa-border)] bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-[var(--spa-accent)] hover:shadow-sm" type="button" @click="openEditor(index)"><div class="flex items-center justify-between"><span class="text-xs font-semibold text-[var(--spa-ink-muted)]">Par {{ index + 1 }}</span><AppIcon name="Pencil" class="size-4 text-[var(--spa-ink-muted)]" /></div><span class="mt-4 block text-base font-semibold text-[var(--spa-ink)]">{{ pair.label_a }} <span class="font-normal text-[var(--spa-ink-muted)]">e</span> {{ pair.label_b }}</span><span class="mt-2 block line-clamp-2 text-sm leading-5 text-[var(--spa-ink-muted)]">{{ pair.concept }}</span></button></div></section>
            <section v-if="games.length" class="surface-panel p-5"><div><h2 class="text-lg font-semibold text-[var(--spa-ink)]">Modelos salvos</h2><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">Edite o conteúdo ou use um modelo em uma nova sessão.</p></div><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><article v-for="game in games" :key="game.id" class="rounded-2xl border border-[var(--spa-border)] bg-white p-4"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold text-[var(--spa-ink)]">{{ game.name }}</h3><p class="mt-1 text-sm text-[var(--spa-ink-muted)]">{{ game.age_group }} · {{ game.pairs_count ?? game.pairs?.length ?? game.pair_count }} pares</p></div><button class="text-xs font-semibold text-red-700" type="button" @click="deleteGame(game)">Excluir</button></div><div class="mt-4 flex flex-wrap gap-2"><button class="btn-secondary" type="button" @click="editGame(game)">Editar</button><button class="btn-secondary" type="button" @click="duplicateGame(game)">Duplicar</button><button class="btn-primary ml-auto" type="button" @click="startSession(game)">Usar em uma sessão</button></div></article></div></section>
        </template>
        <section v-if="activePair" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><div class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-[var(--spa-surface)] p-5 shadow-2xl sm:p-6"><div class="flex items-start justify-between border-b border-[var(--spa-border)] pb-4"><div><p class="section-kicker">Editar par {{ activePairIndex + 1 }}</p><h2 class="mt-1 text-lg font-semibold text-[var(--spa-ink)]">Revise a associação</h2></div><button class="inline-flex size-10 items-center justify-center rounded-xl border border-[var(--spa-border)] text-[var(--spa-ink-muted)]" type="button" aria-label="Fechar" @click="closeEditor"><AppIcon name="X" class="size-5" /></button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="field-label">Carta A<input v-model="activePair.label_a" class="field-input mt-1" /></label><label class="field-label">Carta B<input v-model="activePair.label_b" class="field-input mt-1" /></label></div><label class="field-label mt-4 block">Conceito trabalhado<textarea v-model="activePair.concept" class="field-input mt-1 min-h-24" /></label><label class="field-label mt-4 block">Feedback ao encontrar o par<textarea v-model="activePair.feedback" class="field-input mt-1 min-h-24" /></label><div class="mt-5 flex justify-end"><button class="btn-primary" type="button" @click="closeEditor">Concluir edição</button></div></div></section>
        <section v-if="editingId" class="fixed inset-0 z-40 flex items-center justify-center bg-slate-900/40 p-4"><div class="max-h-[92vh] w-full max-w-6xl overflow-y-auto rounded-3xl bg-[var(--spa-surface)] p-5 shadow-2xl sm:p-6"><div class="flex items-start justify-between gap-4 border-b border-[var(--spa-border)] pb-4"><div><p class="section-kicker">Editar modelo</p><h2 class="mt-1 text-xl font-semibold text-[var(--spa-ink)]">Atualize o conteúdo da atividade</h2></div><button class="inline-flex size-10 shrink-0 items-center justify-center rounded-xl border border-[var(--spa-border)] text-[var(--spa-ink-muted)]" type="button" aria-label="Fechar editor" @click="closeModelEditor"><AppIcon name="X" class="size-5" /></button></div><div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label class="field-label">Nome<input v-model="form.name" class="field-input mt-1" /></label><label class="field-label">Faixa etária<select v-model="form.age_group" class="field-input mt-1"><option>Criança</option><option>Adolescente</option><option>Adulto</option></select></label><label class="field-label">Tema<input v-model="form.theme" class="field-input mt-1" /></label><label class="field-label">Dificuldade<select v-model="form.difficulty" class="field-input mt-1"><option>Fácil</option><option>Média</option><option>Difícil</option></select></label></div><div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><button v-for="(pair, index) in pairs" :key="index" class="rounded-2xl border border-[var(--spa-border)] bg-white p-4 text-left transition hover:border-[var(--spa-accent)]" type="button" @click="openEditor(index)"><span class="text-xs font-semibold text-[var(--spa-ink-muted)]">Par {{ index + 1 }}</span><span class="mt-2 block font-semibold text-[var(--spa-ink)]">{{ pair.label_a }} e {{ pair.label_b }}</span><span class="mt-1 block line-clamp-2 text-sm text-[var(--spa-ink-muted)]">{{ pair.concept }}</span></button></div><div class="mt-6 flex justify-end gap-3 border-t border-[var(--spa-border)] pt-5"><button class="btn-secondary" type="button" @click="closeModelEditor">Cancelar</button><button class="btn-primary" type="button" :disabled="saving || !form.name.trim()" @click="saveGame">{{ saving ? 'Salvando...' : 'Atualizar modelo' }}</button></div></div></section>
    </main>
</template>
